package softwareProjectManagement;

public class Main {
	
	//VERY IMPORTANT NOTE:
	
	/*
	 *  THERE IS THREE ESSENTIAL PARTS FOR MAKING A UI AND DB BASED PROJECT
	 *
	 *	ACTUALLY THE CODE IS A FILTER OR ORGANIZATOR FOR STORING, RECEIVING OR PROTECTING THE DATA
	 * 	
	 * 	SO THE ESSENTIAL PARTS ARE EXISTING IN THIS SCHEMA GIVEN BELOW
	 * 	
	 * 	
	 * 	UI -----> CODE -------> DATABASE
	 *	
	 *	
	 *  DESINGING UI IS SIMPLE BUT FOR CODE AND DATABASE, THEY SHOULD BE CREATED AS CONNECTED 	
	 * 	
	 *  DATABASE ALSO HAS ITS OWN LANGUAGE AND STRUCTURE SO AT THE BEGINNING OF THE PROJECT AS A TEAM 
	 * 	
	 *  WE HAVE TO BE CAREFUL IN ADVANCE WHILE CREATING THE STRUCTURE. 
	 * 
	 * 
	 */
	
	
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
			
	}

}
